version: "2"

services:

  app:
    build: .
    image: tobinquadros/clearance:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/github.com/tobinquadros/clearance
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./data:/data

  cache:
    image: redis:alpine
