version: "3"

services:

  app:
    build: .
    depends_on:
      - db
      - cache
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/go/src/github.com/tobinquadros/clearance

  db:
    env_file:
      - .env
    image: postgres:9.6
    volumes:
      - ./data:/data

  cache:
    image: redis:alpine
