version: "2"

services:

  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./build/linux:/usr/local/bin/
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./data:/data

  cache:
    image: redis:alpine
